"""Add like_ganre

Revision ID: 1dd1a51e18f2
Revises: 2b3f549a3d3b
Create Date: 2025-06-13 14:43:34.246421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd1a51e18f2'
down_revision = '2b3f549a3d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('like_ganre', sa.Enum('ACTION', 'COMEDY', 'DRAMA', 'FANTASY', 'HORROR', 'ROMANCE', 'THRILLER', 'DETECTIVE', name='ganrebook'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'like_ganre')
    # ### end Alembic commands ###
