"""add new column book_data_output

Revision ID: 1fc7ea0b97df
Revises: 4e04fde0fbf7
Create Date: 2025-07-14 16:02:53.726620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc7ea0b97df'
down_revision = '4e04fde0fbf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('book_data_ouput', sa.Integer(), server_default='30', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'book_data_ouput')
    # ### end Alembic commands ###
