"""Del like_ganre

Revision ID: 2b3f549a3d3b
Revises: 5319f611dc8b
Create Date: 2025-06-13 14:42:10.893992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3f549a3d3b'
down_revision = '5319f611dc8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket', sa.Column('date_put_book', sa.DateTime(), nullable=False))
    op.drop_column('user', 'like_ganre')
    op.drop_column('user', 'total_books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('total_books', sa.INTEGER(), nullable=False))
    op.add_column('user', sa.Column('like_ganre', sa.VARCHAR(length=8), nullable=False))
    op.drop_column('basket', 'date_put_book')
    # ### end Alembic commands ###
