"""delete new column book_data_output

Revision ID: 4e04fde0fbf7
Revises: d6f622127fdb
Create Date: 2025-07-14 15:56:16.421469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e04fde0fbf7'
down_revision = 'd6f622127fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'book_data_ouput')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('book_data_ouput', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
