"""add new column book_data_output

Revision ID: d6f622127fdb
Revises: 03ea0737617f
Create Date: 2025-07-14 15:54:31.912619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f622127fdb'
down_revision = '03ea0737617f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('book_data_ouput', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'book_data_ouput')
    # ### end Alembic commands ###
